--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Ubuntu 14.17-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-23 22:43:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 245 (class 1255 OID 31564)
-- Name: add_app_user(); Type: FUNCTION; Schema: public; Owner: group34
--

CREATE FUNCTION public.add_app_user() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
	INSERT INTO public.appuser(username, biography, is_database_admin, creation_date, karma, auth_id)
	VALUES
	(NEW.username, '', NEW.is_superuser, NEW.date_joined, 0, NEW.id);
	RETURN NEW;
END;
$$;


ALTER FUNCTION public.add_app_user() OWNER TO group34;

--
-- TOC entry 247 (class 1255 OID 31723)
-- Name: decrement_member_count(); Type: FUNCTION; Schema: public; Owner: group34
--

CREATE FUNCTION public.decrement_member_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
	UPDATE Community SET member_count = member_count - 1
	WHERE Community.community_id = OLD.community_id;
	RETURN OLD;
END;
$$;


ALTER FUNCTION public.decrement_member_count() OWNER TO group34;

--
-- TOC entry 246 (class 1255 OID 31719)
-- Name: increment_member_count(); Type: FUNCTION; Schema: public; Owner: group34
--

CREATE FUNCTION public.increment_member_count() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
	BEGIN
		UPDATE Community SET member_count = member_count + 1 
		WHERE Community.community_id = NEW.community_id;
		RETURN NEW;
	END;
$$;


ALTER FUNCTION public.increment_member_count() OWNER TO group34;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 18907)
-- Name: appuser; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.appuser (
    user_id integer NOT NULL,
    username character varying(50) NOT NULL,
    biography text,
    is_database_admin boolean DEFAULT false,
    creation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    karma integer DEFAULT 0,
    auth_id integer
);


ALTER TABLE public.appuser OWNER TO group34;

--
-- TOC entry 209 (class 1259 OID 18906)
-- Name: appuser_user_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

CREATE SEQUENCE public.appuser_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.appuser_user_id_seq OWNER TO group34;

--
-- TOC entry 3534 (class 0 OID 0)
-- Dependencies: 209
-- Name: appuser_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: group34
--

ALTER SEQUENCE public.appuser_user_id_seq OWNED BY public.appuser.user_id;


--
-- TOC entry 233 (class 1259 OID 31428)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO group34;

--
-- TOC entry 232 (class 1259 OID 31427)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 31436)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO group34;

--
-- TOC entry 234 (class 1259 OID 31435)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 31422)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO group34;

--
-- TOC entry 230 (class 1259 OID 31421)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 31442)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO group34;

--
-- TOC entry 239 (class 1259 OID 31450)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO group34;

--
-- TOC entry 238 (class 1259 OID 31449)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 31441)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 31456)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO group34;

--
-- TOC entry 240 (class 1259 OID 31455)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 18958)
-- Name: comment; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.comment (
    comment_id integer NOT NULL,
    post_id integer,
    user_id integer,
    reply_to_comment_id integer,
    content text NOT NULL,
    creation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    upvotes integer DEFAULT 0,
    downvotes integer DEFAULT 0,
    CONSTRAINT comment_downvotes_check CHECK ((downvotes >= 0)),
    CONSTRAINT comment_upvotes_check CHECK ((upvotes >= 0))
);


ALTER TABLE public.comment OWNER TO group34;

--
-- TOC entry 215 (class 1259 OID 18957)
-- Name: comment_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

CREATE SEQUENCE public.comment_comment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.comment_comment_id_seq OWNER TO group34;

--
-- TOC entry 3535 (class 0 OID 0)
-- Dependencies: 215
-- Name: comment_comment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: group34
--

ALTER SEQUENCE public.comment_comment_id_seq OWNED BY public.comment.comment_id;


--
-- TOC entry 218 (class 1259 OID 19016)
-- Name: comment_interaction; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.comment_interaction (
    user_id integer NOT NULL,
    comment_id integer NOT NULL,
    interaction_type character varying(50)
);


ALTER TABLE public.comment_interaction OWNER TO group34;

--
-- TOC entry 212 (class 1259 OID 18921)
-- Name: community; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.community (
    community_id integer NOT NULL,
    name character varying(100) NOT NULL,
    about text,
    member_count integer DEFAULT 0,
    CONSTRAINT community_member_count_check CHECK ((member_count >= 0))
);


ALTER TABLE public.community OWNER TO group34;

--
-- TOC entry 211 (class 1259 OID 18920)
-- Name: community_community_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

CREATE SEQUENCE public.community_community_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.community_community_id_seq OWNER TO group34;

--
-- TOC entry 3536 (class 0 OID 0)
-- Dependencies: 211
-- Name: community_community_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: group34
--

ALTER SEQUENCE public.community_community_id_seq OWNED BY public.community.community_id;


--
-- TOC entry 221 (class 1259 OID 20565)
-- Name: community_list; Type: VIEW; Schema: public; Owner: group34
--

CREATE VIEW public.community_list AS
 SELECT community.name,
    community.community_id
   FROM public.community;


ALTER VIEW public.community_list OWNER TO group34;

--
-- TOC entry 217 (class 1259 OID 18986)
-- Name: usercommunity; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.usercommunity (
    user_id integer NOT NULL,
    community_id integer NOT NULL,
    role character varying(50)
);


ALTER TABLE public.usercommunity OWNER TO group34;

--
-- TOC entry 224 (class 1259 OID 26955)
-- Name: community_member_count; Type: VIEW; Schema: public; Owner: group34
--

CREATE VIEW public.community_member_count AS
 SELECT c.community_id,
    c.name,
    count(uc.user_id) AS member_count
   FROM (public.usercommunity uc
     LEFT JOIN public.community c ON ((uc.community_id = c.community_id)))
  GROUP BY c.community_id, c.name
  ORDER BY (count(uc.user_id)) DESC;


ALTER VIEW public.community_member_count OWNER TO group34;

--
-- TOC entry 220 (class 1259 OID 20561)
-- Name: community_names; Type: VIEW; Schema: public; Owner: group34
--

CREATE VIEW public.community_names AS
 SELECT community.name
   FROM public.community;


ALTER VIEW public.community_names OWNER TO group34;

--
-- TOC entry 214 (class 1259 OID 18934)
-- Name: posts; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.posts (
    post_id integer NOT NULL,
    user_id integer,
    community_id integer,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    creation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    upvotes integer DEFAULT 0,
    downvotes integer DEFAULT 0,
    CONSTRAINT posts_downvotes_check CHECK ((downvotes >= 0)),
    CONSTRAINT posts_upvotes_check CHECK ((upvotes >= 0))
);


ALTER TABLE public.posts OWNER TO group34;

--
-- TOC entry 223 (class 1259 OID 26933)
-- Name: community_post_count; Type: VIEW; Schema: public; Owner: group34
--

CREATE VIEW public.community_post_count AS
 SELECT c.community_id,
    c.name AS community_name,
    count(p.post_id) AS total_posts
   FROM (public.community c
     LEFT JOIN public.posts p ON ((c.community_id = p.community_id)))
  GROUP BY c.community_id, c.name;


ALTER VIEW public.community_post_count OWNER TO group34;

--
-- TOC entry 243 (class 1259 OID 31514)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO group34;

--
-- TOC entry 242 (class 1259 OID 31513)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 31414)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO group34;

--
-- TOC entry 228 (class 1259 OID 31413)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 31406)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO group34;

--
-- TOC entry 226 (class 1259 OID 31405)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 31542)
-- Name: django_session; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO group34;

--
-- TOC entry 225 (class 1259 OID 26976)
-- Name: post_comment_count; Type: VIEW; Schema: public; Owner: group34
--

CREATE VIEW public.post_comment_count AS
 SELECT p.post_id,
    p.title,
    count(c.comment_id) AS comment_count
   FROM (public.posts p
     LEFT JOIN public.comment c ON ((p.post_id = c.comment_id)))
  GROUP BY p.post_id, p.title;


ALTER VIEW public.post_comment_count OWNER TO group34;

--
-- TOC entry 219 (class 1259 OID 20546)
-- Name: post_interaction; Type: TABLE; Schema: public; Owner: group34
--

CREATE TABLE public.post_interaction (
    user_id integer NOT NULL,
    post_id integer NOT NULL,
    interaction_type character varying(50)
);


ALTER TABLE public.post_interaction OWNER TO group34;

--
-- TOC entry 213 (class 1259 OID 18933)
-- Name: posts_post_id_seq; Type: SEQUENCE; Schema: public; Owner: group34
--

CREATE SEQUENCE public.posts_post_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.posts_post_id_seq OWNER TO group34;

--
-- TOC entry 3537 (class 0 OID 0)
-- Dependencies: 213
-- Name: posts_post_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: group34
--

ALTER SEQUENCE public.posts_post_id_seq OWNED BY public.posts.post_id;


--
-- TOC entry 222 (class 1259 OID 20569)
-- Name: user_list; Type: VIEW; Schema: public; Owner: group34
--

CREATE VIEW public.user_list AS
 SELECT appuser.username,
    appuser.user_id
   FROM public.appuser;


ALTER VIEW public.user_list OWNER TO group34;

--
-- TOC entry 3274 (class 2604 OID 18910)
-- Name: appuser user_id; Type: DEFAULT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.appuser ALTER COLUMN user_id SET DEFAULT nextval('public.appuser_user_id_seq'::regclass);


--
-- TOC entry 3284 (class 2604 OID 18961)
-- Name: comment comment_id; Type: DEFAULT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.comment ALTER COLUMN comment_id SET DEFAULT nextval('public.comment_comment_id_seq'::regclass);


--
-- TOC entry 3278 (class 2604 OID 18924)
-- Name: community community_id; Type: DEFAULT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.community ALTER COLUMN community_id SET DEFAULT nextval('public.community_community_id_seq'::regclass);


--
-- TOC entry 3280 (class 2604 OID 18937)
-- Name: posts post_id; Type: DEFAULT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.posts ALTER COLUMN post_id SET DEFAULT nextval('public.posts_post_id_seq'::regclass);


--
-- TOC entry 3295 (class 2606 OID 18917)
-- Name: appuser appuser_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.appuser
    ADD CONSTRAINT appuser_pkey PRIMARY KEY (user_id);


--
-- TOC entry 3297 (class 2606 OID 18919)
-- Name: appuser appuser_username_key; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.appuser
    ADD CONSTRAINT appuser_username_key UNIQUE (username);


--
-- TOC entry 3325 (class 2606 OID 31540)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 3330 (class 2606 OID 31471)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 3333 (class 2606 OID 31440)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3327 (class 2606 OID 31432)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3320 (class 2606 OID 31462)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 3322 (class 2606 OID 31426)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3341 (class 2606 OID 31454)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3344 (class 2606 OID 31486)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 3335 (class 2606 OID 31446)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 3347 (class 2606 OID 31460)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3350 (class 2606 OID 31500)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 3338 (class 2606 OID 31535)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 3305 (class 2606 OID 18970)
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (comment_id);


--
-- TOC entry 3299 (class 2606 OID 18932)
-- Name: community community_name_key; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.community
    ADD CONSTRAINT community_name_key UNIQUE (name);


--
-- TOC entry 3301 (class 2606 OID 18930)
-- Name: community community_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.community
    ADD CONSTRAINT community_pkey PRIMARY KEY (community_id);


--
-- TOC entry 3353 (class 2606 OID 31521)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3315 (class 2606 OID 31420)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 3317 (class 2606 OID 31418)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 3313 (class 2606 OID 31412)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3357 (class 2606 OID 31548)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 3309 (class 2606 OID 19020)
-- Name: comment_interaction interaction_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.comment_interaction
    ADD CONSTRAINT interaction_pkey PRIMARY KEY (user_id, comment_id);


--
-- TOC entry 3311 (class 2606 OID 20550)
-- Name: post_interaction post_interaction_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.post_interaction
    ADD CONSTRAINT post_interaction_pkey PRIMARY KEY (user_id, post_id);


--
-- TOC entry 3303 (class 2606 OID 18946)
-- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_pkey PRIMARY KEY (post_id);


--
-- TOC entry 3307 (class 2606 OID 18990)
-- Name: usercommunity usercommunity_pkey; Type: CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.usercommunity
    ADD CONSTRAINT usercommunity_pkey PRIMARY KEY (user_id, community_id);


--
-- TOC entry 3323 (class 1259 OID 31541)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 3328 (class 1259 OID 31482)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 3331 (class 1259 OID 31483)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 3318 (class 1259 OID 31468)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 3339 (class 1259 OID 31498)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 3342 (class 1259 OID 31497)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 3345 (class 1259 OID 31512)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 3348 (class 1259 OID 31511)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 3336 (class 1259 OID 31536)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 3351 (class 1259 OID 31532)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 3354 (class 1259 OID 31533)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 3355 (class 1259 OID 31550)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 3358 (class 1259 OID 31549)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: group34
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 3382 (class 2620 OID 31565)
-- Name: auth_user on_account_creation; Type: TRIGGER; Schema: public; Owner: group34
--

CREATE TRIGGER on_account_creation AFTER INSERT ON public.auth_user FOR EACH ROW EXECUTE FUNCTION public.add_app_user();


--
-- TOC entry 3380 (class 2620 OID 31720)
-- Name: usercommunity on_member_join; Type: TRIGGER; Schema: public; Owner: group34
--

CREATE TRIGGER on_member_join AFTER INSERT ON public.usercommunity FOR EACH ROW EXECUTE FUNCTION public.increment_member_count();


--
-- TOC entry 3381 (class 2620 OID 31724)
-- Name: usercommunity on_member_leave; Type: TRIGGER; Schema: public; Owner: group34
--

CREATE TRIGGER on_member_leave AFTER DELETE ON public.usercommunity FOR EACH ROW EXECUTE FUNCTION public.decrement_member_count();


--
-- TOC entry 3372 (class 2606 OID 31477)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3373 (class 2606 OID 31472)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3359 (class 2606 OID 31566)
-- Name: appuser auth_id; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.appuser
    ADD CONSTRAINT auth_id FOREIGN KEY (auth_id) REFERENCES public.auth_user(id) ON DELETE CASCADE;


--
-- TOC entry 3371 (class 2606 OID 31463)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3374 (class 2606 OID 31492)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3375 (class 2606 OID 31487)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3376 (class 2606 OID 31506)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3377 (class 2606 OID 31501)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3362 (class 2606 OID 18971)
-- Name: comment comment_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(post_id) ON DELETE CASCADE;


--
-- TOC entry 3363 (class 2606 OID 18981)
-- Name: comment comment_reply_to_comment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_reply_to_comment_id_fkey FOREIGN KEY (reply_to_comment_id) REFERENCES public.comment(comment_id) ON DELETE CASCADE;


--
-- TOC entry 3364 (class 2606 OID 18976)
-- Name: comment comment_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.appuser(user_id) ON DELETE CASCADE;


--
-- TOC entry 3378 (class 2606 OID 31522)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3379 (class 2606 OID 31527)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3367 (class 2606 OID 19026)
-- Name: comment_interaction interaction_comment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.comment_interaction
    ADD CONSTRAINT interaction_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.comment(comment_id) ON DELETE CASCADE;


--
-- TOC entry 3368 (class 2606 OID 19021)
-- Name: comment_interaction interaction_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.comment_interaction
    ADD CONSTRAINT interaction_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.appuser(user_id) ON DELETE CASCADE;


--
-- TOC entry 3369 (class 2606 OID 20556)
-- Name: post_interaction post_interaction_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.post_interaction
    ADD CONSTRAINT post_interaction_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(post_id) ON DELETE CASCADE;


--
-- TOC entry 3370 (class 2606 OID 20551)
-- Name: post_interaction post_interaction_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.post_interaction
    ADD CONSTRAINT post_interaction_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.appuser(user_id) ON DELETE CASCADE;


--
-- TOC entry 3360 (class 2606 OID 18952)
-- Name: posts posts_community_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.community(community_id) ON DELETE CASCADE;


--
-- TOC entry 3361 (class 2606 OID 18947)
-- Name: posts posts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.posts
    ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.appuser(user_id) ON DELETE CASCADE;


--
-- TOC entry 3365 (class 2606 OID 18996)
-- Name: usercommunity usercommunity_community_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.usercommunity
    ADD CONSTRAINT usercommunity_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.community(community_id) ON DELETE CASCADE;


--
-- TOC entry 3366 (class 2606 OID 18991)
-- Name: usercommunity usercommunity_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: group34
--

ALTER TABLE ONLY public.usercommunity
    ADD CONSTRAINT usercommunity_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.appuser(user_id) ON DELETE CASCADE;


--
-- TOC entry 3533 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2025-04-23 22:43:52

--
-- PostgreSQL database dump complete
--

